### ISSUE TITLE
Fix uploaded files on the interface which contains blanks

### ISSUE THREAD

**Issue by Elizemiku** [labbcb/GA4GHshiny#10]
In the column option Gene Symbols File, is uploaded a plain text file containing list of Gene Symbols (one gene per line) to search for variants, the function `fileInput()`should read the file to search the genes in Variants( ` DT::dataTableOutput("dt.variants")`,) ignoring or removing blanks that contain in the file.

**Comment by wdesouza** [comment]
I didn't understand this issue. Can you explain more by adding a reproducible example of this issue?

**Comment by wdesouza** [comment]
This file contains many valid gene symbols but with some problems that app should take care: [genes.txt](https://github.com/labbcb/GA4GHshiny/files/1376065/genes.txt)

Problems:

- spaces in the beginning of the line
- spaces after gene symbol
- lowercase gene names

Running GA4GHshiny:

``` r
library(GA4GHshiny)
app("http://1kgenomes.ga4gh.org/", orgDb = "org.Hs.eg.db", txDb = "TxDb.Hsapiens.UCSC.hg19.knownGene")
```

Genomic Feature = Genes.
It should return 546 + 1365 + 165 + 2214 = 4290 variants.
